services:
  postgis:
    image: postgis/postgis:15-3.5
    container_name: postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgis_data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - internal

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
    - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgis
    networks:
      - internal

  geoserver:
    image: kartoza/geoserver:2.22.2
    container_name: geoserver
    environment:
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - ${GEOSERVER_WEB_PATH}:/usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
    depends_on:
      - postgis
    restart: unless-stopped
    networks:
      - internal

  gdal:
    image: osgeo/gdal:ubuntu-small-3.6.3
    container_name: gdal
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - /root/accessibility-project1/data:/data 
      - /root/accessibility-project1/backend:/backend
    restart: unless-stopped
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d/default.conf:ro
      - /root/accessibility-project1/backend/certs:/etc/nginx/certs:ro
    depends_on:
      - geoserver
      - django
    restart: unless-stopped
    networks:
      - internal

  django:
    build:
      context: ./django_app
      dockerfile: dockerfile
    container_name: django
    volumes:
      - /root/accessibility-project1/backend/django_app:/app
    env_file:
      - .env
    command: gunicorn webgis_project.wsgi:application --bind 0.0.0.0:8000
    networks:
      - internal

volumes:
  postgis_data:
  geoserver_data:
  pgadmin_data:

networks:
  internal:
    driver: bridge
