version: "3.8"

services:
  postgis:
    image: postgis/postgis:15-3.5
    container_name: postgis_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    restart: unless-stopped

  geoserver:
    image: kartoza/geoserver:2.22.2
    container_name: geoserver
    environment:
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - geoserver_data:/opt/geoserver/data_dir
      - /root/accessibility-project1/backend/web.xml:/usr/local/tomcat/webapps/geoserver/WEB-INF/web.xml
    depends_on:
      - postgis
    restart: unless-stopped

  gdal:
    image: osgeo/gdal:ubuntu-small-3.6.3
    container_name: gdal
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
    - /root/accessibility-project1/data:/data 
    - /root/accessibility-project1/backend:/backend
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/accessibility-project1/backend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /root/accessibility-project1/backend/certs:/etc/nginx/certs:ro
    depends_on:
      - geoserver
    restart: unless-stopped

  django:
    build:
      context: ./django_app
      dockerfile: dockerfile
    container_name: django_app
    volumes:
      - /root/accessibility-project1/backend/django_app:/app
    env_file:
      - /root/accessibility-project1/backend/.env
    command: gunicorn webgis_project.wsgi:application --bind 0.0.0.0:8000


volumes:
  postgis_data:
  geoserver_data: