version: "3.8"

services:
  postgis:
    image: postgis/postgis:15-3.5
    container_name: postgis_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgis_data:/var/lib/postgresql/data
    restart: unless-stopped

  geoserver:
    image: kartoza/geoserver:2.22.2
    container_name: geoserver
    environment:
      GEOSERVER_ADMIN_USER: ${GEOSERVER_ADMIN_USER}
      GEOSERVER_ADMIN_PASSWORD: ${GEOSERVER_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    volumes:
      - geoserver_data:/var/local/geoserver_data
    depends_on:
      - postgis
    restart: unless-stopped

  gdal:
    image: osgeo/gdal:ubuntu-small-3.6.3
    container_name: gdal
    entrypoint: ["tail", "-f", "/dev/null"]
    restart: unless-stopped

volumes:
  postgis_data:
  geoserver_data: